StringTable {
 ItemClassName "DefaultStringTableItem"
 Items {
  DefaultStringTableItem "{6722F99CB67E4063}" {
   Id "DF-Weapon-C7NLD_Description"
   Target_en_us "Dutch army standard issue rifle"
  }
  DefaultStringTableItem "{6722F99CB2B14A78}" {
   Id "DF-Weapon-C7NLD_Name"
   Target_en_us "C7NLD"
  }
  DefaultStringTableItem "{6722F99CA15651F3}" {
   Id "DF-Weapon-C8NLD_Name"
   Target_en_us "C8NLD"
  }
 }
}